import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import NavBar from '../components/navBar'
import Link from 'next/link'
import Footer from '../components/footer'
import Carousel from '../components/carousel'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Fioro Foods</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <NavBar></NavBar>

      <main className={styles.main}>
        <Carousel>
          
        </Carousel>
         {/*  Animated Carrousel
        <div className='border-4 border-purple-400 w-full h-auto'>
          <Image src={'/hand_micro.jpg'} alt='carousel pic' width={750} height={500}/>
        </div> */}
      </main>

      <Footer></Footer>

    </div>
  )
}

